### ISSUE TITLE
Serialization_DeserializedValueEqualsSerializedValue Test Serializing/Deserializing Value Issues

### ISSUE THREAD

**Issue by Cassidie** [kevinphelps/Xtensions#2]
This tests fails for my value object, whose value is a Dictionary. Serializing it and deserializing it doesn't produce an equal object.

Example test failure output:
![image](https://user-images.githubusercontent.com/14021137/65431107-8d9f0d00-ddde-11e9-935b-aedd53fbea65.png)

**Comment by kevinbuhmann** [comment]
I will get with you at work.
